import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
process.env.KM_DATA_DIR = path.resolve('test/consultant-data');
const { cfg } = await import('../src/config.js'); cfg.dataDir = path.resolve('test/consultant-data');
const store = await import('../src/store.js');
const { buildDocx } = await import('../src/files/docs.js');
const { inspectOffice, reviseOffice, appendImageDocx } = await import('../src/files/office.js');
const { readBuffer } = await import('../src/files/readers.js');
const { nextSteps, evidenceText } = await import('../src/consultant.js');
const { runTask } = await import('../src/tasks.js');
const { onCommand, channelAccess } = await import('../src/brain.js');
const LLM = await import('../src/llm.js');
const { default: JSZip } = await import('jszip');
const { default: ExcelJS } = await import('exceljs');
const { default: PptxGenJS } = await import('pptxgenjs');
const { createCanvas } = await import('@napi-rs/canvas');
let count = 0; const check = (ok, label) => { assert.ok(ok, label); console.log('✔ ' + label); count++; };
const canvas = createCanvas(32, 32); canvas.getContext('2d').fillRect(0, 0, 32, 32); const png = canvas.toBuffer('image/png');
const base = await buildDocx('局部修改測試', [{ p: '保留段落' }, { p: '只修改這段' }]);
const withImage = await appendImageDocx(base, png, '情境示意圖');
const zip = await JSZip.loadAsync(withImage); const media = Object.keys(zip.files).find(n => /word\/media\/.+\.png/.test(n));
check(media && (await zip.file(media).async('nodebuffer')).equals(png), 'Word 內嵌實際 PNG');
check((await zip.file('word/_rels/document.xml.rels').async('string')).includes('relationships/image'), 'Word 圖片引用有效');
const info = await inspectOffice(withImage, 'docx'), target = info.parts[0].paragraphs.find(p => p.text === '只修改這段');
const revised = await reviseOffice(withImage, 'docx', [{ part: info.parts[0].name, index: target.index, original: target.text, replacement: '修改後 & 文字' }]);
const edited = await inspectOffice(revised, 'docx');
check(edited.parts[0].paragraphs.some(p => p.text === '修改後 & 文字'), '精確段落修改與 XML 字元處理');
check(edited.parts[0].paragraphs.some(p => p.text === '保留段落'), '未指定段落保持原文');
for (const name of Object.keys(zip.files).filter(n => !zip.files[n].dir && n !== 'word/document.xml')) assert.deepEqual(await edited.zip.file(name).async('nodebuffer'), await zip.file(name).async('nodebuffer'));
check(true, '所有其他文件部件、樣式、圖片逐位元保持');
await assert.rejects(reviseOffice(withImage, 'docx', [{ part: info.parts[0].name, index: target.index, original: '不符原文', replacement: '改' }])); check(true, '原文不符拒絕修改');
const wordText = await readBuffer('source.docx', withImage); check(wordText.text.includes('段落') && wordText.text.includes('保留段落'), 'Word 來源段落索引');
const wb = new ExcelJS.Workbook(), sheet = wb.addWorksheet('成本'); sheet.getCell('A1').value = '單價'; sheet.getCell('B2').value = { formula: '20*3', result: 60 };
const excel = await readBuffer('cost.xlsx', Buffer.from(await wb.xlsx.writeBuffer())); check(excel.text.includes('成本!B2') && excel.text.includes('20*3') && excel.text.includes('60'), 'Excel 儲存格位置、公式與快取值');
const ppt = new PptxGenJS(); ppt.addSlide().addText('第一頁保留', { x: 1, y: 1, w: 4, h: 1 }); ppt.addSlide().addText('第二頁修改', { x: 1, y: 1, w: 4, h: 1 });
const pptBuffer = Buffer.from(await ppt.write({ outputType: 'nodebuffer' })); const pptText = await readBuffer('slides.pptx', pptBuffer); check(pptText.text.includes('投影片 2') && pptText.text.includes('第二頁修改'), 'PPTX 頁面位置與文字讀取');
const pptInfo = await inspectOffice(pptBuffer, 'pptx'), slide2 = pptInfo.parts[1].paragraphs.find(p => p.text === '第二頁修改');
const pptRevised = await reviseOffice(pptBuffer, 'pptx', [{ part: pptInfo.parts[1].name, index: slide2.index, original: slide2.text, replacement: '第二頁已修改' }]);
const pptEdit = await inspectOffice(pptRevised, 'pptx'); check((await pptEdit.zip.file(pptInfo.parts[0].name).async('nodebuffer')).equals(await pptInfo.zip.file(pptInfo.parts[0].name).async('nodebuffer')), '修改第二頁時第一頁完全保留');
function blankPdf() {
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << >> /Contents 4 0 R >>', '<< /Length 0 >>\nstream\n\nendstream'];
  let pdf = '%PDF-1.4\n', offsets = [0]; for (let i = 0; i < objects.length; i++) { offsets.push(Buffer.byteLength(pdf)); pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`; }
  const xref = Buffer.byteLength(pdf); pdf += `xref\n0 5\n0000000000 65535 f \n${offsets.slice(1).map(n => String(n).padStart(10, '0') + ' 00000 n \n').join('')}trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return Buffer.from(pdf);
}
let calls = [];
LLM.setLLM({ text: async args => { calls.push(args); return { text: '掃描測試文字 94 人', usage: {}, truncated: false }; } });
const scanned = await readBuffer('scan.pdf', blankPdf()); check(scanned.text.includes('第 1 頁｜OCR') && scanned.text.includes('94 人') && calls[0].images[0].base64, '無文字 PDF 實際渲染成圖片送 OCR 並保留頁碼');
const c = store.createCase('顧問測試', 'test-guild'); c.ownerId = 'owner'; c.ownerName = '顧問'; c.evidence = [{ name: 'cost.xlsx', at: '2026-10-07', text: excel.text }];
const saved = store.saveOutputFile(c.id, '原版.docx', withImage); c.versions = [{ id: 'v-test', kind: 'prep', ...saved, at: new Date().toISOString() }]; store.saveCase(c);
calls.length = 0;
const fifth = await runTask('revise', c, { text: '只改 Word第5段，改為「本次訪談先確認現況與需求」。' }, new AbortController());
const fifthDoc = await inspectOffice(fifth.files[0].buffer, 'docx');
check(calls.length === 0 && fifthDoc.parts[0].paragraphs[4].text === '本次訪談先確認現況與需求', '指定第5段與確切文字直接替換，不讓模型選位置');
for (const para of info.parts[0].paragraphs.filter(x => x.index !== 4)) assert.equal(fifthDoc.parts[0].paragraphs[para.index].text, para.text);
check((await fifthDoc.zip.file(media).async('nodebuffer')).equals(png), '第5段直接修改保留其他段落與圖片');
check(evidenceText(c).includes('成本!B2'), '案件證據保留來源儲存格'); check(nextSteps(c).includes('POC') && nextSteps(c).includes('預算'), '下一步列出缺漏與 POC');
const bundle = await runTask('handover', c, {}, new AbortController()); const archive = await JSZip.loadAsync(bundle.files.find(f => f.name.endsWith('.zip')).buffer);
check(archive.file('交接說明.docx') && archive.file('來源證據.txt') && archive.file('v-test_原版.docx'), '交接 ZIP 有說明、證據、實際文件');
store.getChannel('private').caseId = c.id; store.saveChannels();
const ctx = { channelId: 'private', guildId: 'test-guild', userId: 'owner', userName: '顧問', allowed: true };
check(String(onCommand('access', { mode: 'restricted' }, ctx)).includes('先把 Discord'), '公開頻道不能啟用案件私密限制');
check(onCommand('access', { mode: 'restricted' }, { ...ctx, privateChannel: true }).content.includes('限制'), '案件負責人可綁定私密頻道');
const restricted = store.getCase(c.id); check(channelAccess(restricted, 'private') && !channelAccess(restricted, 'public'), '禁止跨頻道存取限制案件');
check(!store.listCases('test-guild').some(x => x.id === c.id), '限制案件排除於跨案件清單'); check(store.fileIsRestricted(saved.key), '限制案件既有檔案停止公開下载');
const blocked = onCommand('use', { name: c.name }, { ...ctx, channelId: 'public' }); check(blocked.includes('私密頻道'), '切換限制案件不能繞過頻道限制');
check(onCommand('versions', { name: 'v-test' }, ctx).files[0].buffer.equals(withImage), '私密頻道可下載原版');
console.log(`Passed ${count} consultant checks.`);
const { onMessage } = await import('../src/brain.js');
const posts = [], io = { channelId: 'private', say: async text => posts.push({ content: text }), typing: () => () => {}, post: async payload => { posts.push(payload); return { edit: async update => posts.push(update) }; } };
LLM.setLLM({ text: async () => ({ text: '不在範圍<<<KM_ACTIONS>>>\n{"in_scope":false,"tasks":[]}', usage: {} }) });
const originalFetch = globalThis.fetch;
globalThis.fetch = async () => new Response(JSON.stringify({ data: [{ b64_json: png.toString('base64') }] }), { status: 200, headers: { 'content-type': 'application/json' } });
cfg.imageModel = 'test-image';
const message = { id: 'test-image-' + Date.now(), channelId: 'private', guildId: 'test-guild', author: { id: 'owner', name: '顧問' }, text: '請在訪綱加入企業主管喝咖啡的示意圖', mentionsMe: true, allowed: true, attachments: [] };
await onMessage(message, io);
check(posts.some(p => p.files?.some(f => f.name.endsWith('.png'))) && posts.some(p => p.files?.some(f => f.name.endsWith('.docx'))), '路由即使婉拒，文件配圖明確交辦仍實際交付 PNG 與 Word');
const emittedWord = posts.flatMap(p => p.files || []).find(f => f.name.endsWith('.docx'));
check(Object.keys((await JSZip.loadAsync(emittedWord.buffer)).files).some(n => n.startsWith('word/media/') && n.endsWith('.png')), 'Discord 交付的 Word 確實含圖片');
const beforeVersions = store.getCase(c.id).versions.length; posts.length = 0;
globalThis.fetch = async () => new Response('{}', { status: 503 });
await onMessage({ ...message, id: message.id + '-fail' }, io);
check(posts.some(p => p.content?.includes('沒有完成')) && !posts.some(p => p.files?.length) && store.getCase(c.id).versions.length === beforeVersions, '圖片 API 失敗不交付空配圖文件、不記錄成功版本');
globalThis.fetch = originalFetch;
posts.length = 0;
LLM.setLLM({ text: async () => { throw new Error('版本查詢不應呼叫模型'); } });
await onMessage({ ...message, id: message.id + '-versions', text: '/孔明 文件版本' }, io);
const versionReply = posts.find(p => p.buttons?.some(b => b.id.startsWith('km:version:')));
check(versionReply?.content.includes('v-test'), '一般文字文件版本直接查真實版本，不呼叫模型');
const { onButton } = await import('../src/brain.js');
posts.length = 0;
const downloaded = await onButton(`km:version:${c.id}:v-test`, { id: 'owner', guildId: 'test-guild', allowed: true }, io);
check(downloaded.text.includes('已傳送') && posts[0].files[0].buffer.equals(withImage), '版本下載按鈕交付正確原始檔');
const deniedVersion = await onButton(`km:version:${c.id}:v-test`, { id: 'other', guildId: 'other-guild', allowed: true }, io);
check(deniedVersion.text.includes('不屬於'), '版本下載按鈕拒絕其他伺服器存取');
check(/管理權限/.test((await onButton(`km:undo:${c.id}:unknown`, { id: 'owner', guildId: c.guildId, allowed: true }, io)).text), '缺少管理權限資訊不能復原');
check(/顧問身分組/.test((await onButton(`km:pend:${c.id}:unknown:y`, { id: 'owner', guildId: c.guildId, allowed: true }, io)).text), '缺少管理權限資訊不能核准');
check(/伺服器/.test((await onButton(`km:pend:${c.id}:unknown:y`, { id: 'owner', guildId: 'foreign', admin: true, allowed: true }, io)).text), '跨伺服器確認按鈕遭拒');
console.log(`Total ${count} consultant checks passed.`);
const revisedSaved = store.saveOutputFile(c.id, '最新修改版.docx', revised);
const handoverFixture = { ...c, name: '功能測試公司', profile: { ...c.profile, employees: 94, budget: 300 }, facts: [{ label: '表列設備合計', value: '4萬元', source: '虛構測試資料' }], prep: { title: '已產出的訪綱' }, todos: [{ text: '依需求製作60分鐘訪綱', owner: '孔明', done: false }], versions: [c.versions[0], { id: 'v-new', kind: 'revise', ...revisedSaved, at: new Date().toISOString(), baseVersionId: 'v-test' }, { id: 'old-handover', kind: 'handover', ...saved, name: '舊交接包.docx' }], research: { summary: '不得輸出內部偏好（照做）或其他公司背景' } };
const fixtureBefore = JSON.stringify(handoverFixture);
const cleaned = await runTask('handover', handoverFixture, {}, new AbortController());
const cleanedDoc = await inspectOffice(cleaned.files[0].buffer, 'docx'), cleanedText = cleanedDoc.parts[0].paragraphs.map(x => x.text).join('\n');
check((await cleanedDoc.zip.file('word/document.xml').async('string')).includes('<w:tbl>') && cleanedText.includes('300 萬元') && cleanedText.includes('94 人'), '交接概要使用欄位表格且數字單位正確');
check(cleanedText.includes('296 萬元') && cleanedText.includes('待核准變更 0 項') && cleanedText.includes('目前階段：訪前準備'), '零待核准仍列缺漏與預算用途，階段顯示中文');
check(!cleanedText.includes('照做') && !cleanedText.includes('顧問實務'), '交接不輸出模型內部提示或通用顧問經驗');
check(cleanedText.includes('更新與覆核既有訪綱初稿') && JSON.stringify(handoverFixture) === fixtureBefore, '既有初稿與待更新工作分開，不擅自標記待辦完成');
const cleanedZip = await JSZip.loadAsync(cleaned.files[1].buffer), manifest = JSON.parse(await cleanedZip.file('版本索引.json').async('string'));
check(cleanedZip.file('v-new_最新修改版.docx') && !cleanedZip.file('v-test_原版.docx') && manifest.current.length === 1 && manifest.history.some(x => x.id === 'old-handover'), '修改版取代原版打包，歷史索引和舊交接包明確隔離');
const syntheticBundle = await runTask('handover', { ...c, name: '功能測試公司', research: { summary: '錯誤混入 Keysight 公司背景', sources: [{ title: 'Keysight', url: 'https://example.invalid/unrelated' }] }, versions: [...c.versions, { id: 'bad-research', kind: 'research', key: saved.key, name: '錯誤背景.docx' }] }, {}, new AbortController());
const syntheticWord = await inspectOffice(syntheticBundle.files[0].buffer, 'docx');
const syntheticZip = await JSZip.loadAsync(syntheticBundle.files[1].buffer);
check(!syntheticWord.parts[0].paragraphs.some(x => x.text.includes('Keysight')) && !syntheticZip.file('bad-research_錯誤背景.docx'), '虛構案件交接不混入網路企業背景或研究檔案');
posts.length = 0;
const currentCase = store.getCase(c.id), beforeIngests = currentCase.ingests.length;
globalThis.fetch = async () => new Response(c.name + '\n虛構測試資料\n員工數：94人', { status: 200 });
LLM.setLLM({ text: async args => ({ text: args.label === 'router' ? '因未指定處理方式，目前僅讀取，不寫入案件。<<<KM_ACTIONS>>>\n{"in_scope":false,"attachment_action":"skip","tasks":[]}' : JSON.stringify({ source_title: '虛構測試資料', profile_updates: { employees: 94 }, facts: [], missing: [], doubts: [] }), usage: {} }) });
await onMessage({ ...message, id: message.id + '-ingest', text: '', attachmentMode: 'ingest', attachments: [{ name: '測試資料.txt', url: 'https://example.invalid/test', size: 100 }] }, io);
check(store.getCase(c.id).ingests.length === beforeIngests + 1 && posts.some(p => p.content?.includes('資料建檔') && p.content?.includes('完成')), '按建檔後完整流程完成，即使模型錯稱未指定方式');
globalThis.fetch = originalFetch;
const { honorAttachmentChoice } = await import('../src/brain.js');
check(honorAttachmentChoice({ attachmentMode: 'ingest' }, { name: '功能測試公司' }, [{ kind: 'text', text: '功能測試公司，虛構測試資料，員工94人' }], '因未指定處理方式，目前僅讀取、不寫入案件'), '同名測試附件已選建檔，不能以未指定方式拒絕');
check(!honorAttachmentChoice({ attachmentMode: 'ingest' }, { name: '功能測試公司' }, [{ kind: 'text', text: '銘優科技' }], '內容與功能測試公司不一致'), '其他公司附件不繞過案件不符攔截');
check(!honorAttachmentChoice({}, { name: '功能測試公司' }, [{ kind: 'text', text: '功能測試公司' }], '僅讀取'), '沒有按建檔按鈕不擅自更新案件');
console.log(`Total ${count} consultant checks passed.`);
