import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
process.env.KM_DATA_DIR = path.resolve('test/consultant-data');
const { cfg } = await import('../src/config.js'); cfg.dataDir = path.resolve('test/consultant-data');
const store = await import('../src/store.js');
const { buildDocx } = await import('../src/files/docs.js');
const { inspectOffice, reviseOffice, appendImageDocx } = await import('../src/files/office.js');
const { readBuffer } = await import('../src/files/readers.js');
const { nextSteps, evidenceText } = await import('../src/consultant.js');
const { runTask } = await import('../src/tasks.js');
const { onCommand, channelAccess } = await import('../src/brain.js');
const LLM = await import('../src/llm.js');
const { default: JSZip } = await import('jszip');
const { default: ExcelJS } = await import('exceljs');
const { default: PptxGenJS } = await import('pptxgenjs');
const { createCanvas } = await import('@napi-rs/canvas');
let count = 0; const check = (ok, label) => { assert.ok(ok, label); console.log('✔ ' + label); count++; };
const canvas = createCanvas(32, 32); canvas.getContext('2d').fillRect(0, 0, 32, 32); const png = canvas.toBuffer('image/png');
const base = await buildDocx('局部修改測試', [{ p: '保留段落' }, { p: '只修改這段' }]);
const withImage = await appendImageDocx(base, png, '情境示意圖');
const zip = await JSZip.loadAsync(withImage); const media = Object.keys(zip.files).find(n => /word\/media\/.+\.png/.test(n));
check(media && (await zip.file(media).async('nodebuffer')).equals(png), 'Word 內嵌實際 PNG');
check((await zip.file('word/_rels/document.xml.rels').async('string')).includes('relationships/image'), 'Word 圖片引用有效');
const info = await inspectOffice(withImage, 'docx'), target = info.parts[0].paragraphs.find(p => p.text === '只修改這段');
const revised = await reviseOffice(withImage, 'docx', [{ part: info.parts[0].name, index: target.index, original: target.text, replacement: '修改後 & 文字' }]);
const edited = await inspectOffice(revised, 'docx');
check(edited.parts[0].paragraphs.some(p => p.text === '修改後 & 文字'), '精確段落修改與 XML 字元處理');
check(edited.parts[0].paragraphs.some(p => p.text === '保留段落'), '未指定段落保持原文');
for (const name of Object.keys(zip.files).filter(n => !zip.files[n].dir && n !== 'word/document.xml')) assert.deepEqual(await edited.zip.file(name).async('nodebuffer'), await zip.file(name).async('nodebuffer'));
check(true, '所有其他文件部件、樣式、圖片逐位元保持');
await assert.rejects(reviseOffice(withImage, 'docx', [{ part: info.parts[0].name, index: target.index, original: '不符原文', replacement: '改' }])); check(true, '原文不符拒絕修改');
const wordText = await readBuffer('source.docx', withImage); check(wordText.text.includes('段落') && wordText.text.includes('保留段落'), 'Word 來源段落索引');
const wb = new ExcelJS.Workbook(), sheet = wb.addWorksheet('成本'); sheet.getCell('A1').value = '單價'; sheet.getCell('B2').value = { formula: '20*3', result: 60 };
const excel = await readBuffer('cost.xlsx', Buffer.from(await wb.xlsx.writeBuffer())); check(excel.text.includes('成本!B2') && excel.text.includes('20*3') && excel.text.includes('60'), 'Excel 儲存格位置、公式與快取值');
const ppt = new PptxGenJS(); ppt.addSlide().addText('第一頁保留', { x: 1, y: 1, w: 4, h: 1 }); ppt.addSlide().addText('第二頁修改', { x: 1, y: 1, w: 4, h: 1 });
const pptBuffer = Buffer.from(await ppt.write({ outputType: 'nodebuffer' })); const pptText = await readBuffer('slides.pptx', pptBuffer); check(pptText.text.includes('投影片 2') && pptText.text.includes('第二頁修改'), 'PPTX 頁面位置與文字讀取');
const pptInfo = await inspectOffice(pptBuffer, 'pptx'), slide2 = pptInfo.parts[1].paragraphs.find(p => p.text === '第二頁修改');
const pptRevised = await reviseOffice(pptBuffer, 'pptx', [{ part: pptInfo.parts[1].name, index: slide2.index, original: slide2.text, replacement: '第二頁已修改' }]);
const pptEdit = await inspectOffice(pptRevised, 'pptx'); check((await pptEdit.zip.file(pptInfo.parts[0].name).async('nodebuffer')).equals(await pptInfo.zip.file(pptInfo.parts[0].name).async('nodebuffer')), '修改第二頁時第一頁完全保留');
function blankPdf() {
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << >> /Contents 4 0 R >>', '<< /Length 0 >>\nstream\n\nendstream'];
  let pdf = '%PDF-1.4\n', offsets = [0]; for (let i = 0; i < objects.length; i++) { offsets.push(Buffer.byteLength(pdf)); pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`; }
  const xref = Buffer.byteLength(pdf); pdf += `xref\n0 5\n0000000000 65535 f \n${offsets.slice(1).map(n => String(n).padStart(10, '0') + ' 00000 n \n').join('')}trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return Buffer.from(pdf);
}
let calls = [];
LLM.setLLM({ text: async args => { calls.push(args); return { text: '掃描測試文字 94 人', usage: {}, truncated: false }; } });
const scanned = await readBuffer('scan.pdf', blankPdf()); check(scanned.text.includes('第 1 頁｜OCR') && scanned.text.includes('94 人') && calls[0].images[0].base64, '無文字 PDF 實際渲染成圖片送 OCR 並保留頁碼');
const c = store.createCase('顧問測試', 'test-guild'); c.ownerId = 'owner'; c.ownerName = '顧問'; c.evidence = [{ name: 'cost.xlsx', at: '2026-10-07', text: excel.text }];
const saved = store.saveOutputFile(c.id, '原版.docx', withImage); c.versions = [{ id: 'v-test', kind: 'prep', ...saved, at: new Date().toISOString() }]; store.saveCase(c);
check(evidenceText(c).includes('成本!B2'), '案件證據保留來源儲存格'); check(nextSteps(c).includes('POC') && nextSteps(c).includes('預算'), '下一步列出缺漏與 POC');
const bundle = await runTask('handover', c, {}, new AbortController()); const archive = await JSZip.loadAsync(bundle.files.find(f => f.name.endsWith('.zip')).buffer);
check(archive.file('交接說明.docx') && archive.file('來源證據.txt') && archive.file('v-test_原版.docx'), '交接 ZIP 有說明、證據、實際文件');
store.getChannel('private').caseId = c.id; store.saveChannels();
const ctx = { channelId: 'private', guildId: 'test-guild', userId: 'owner', userName: '顧問', allowed: true };
check(String(onCommand('access', { mode: 'restricted' }, ctx)).includes('先把 Discord'), '公開頻道不能啟用案件私密限制');
check(onCommand('access', { mode: 'restricted' }, { ...ctx, privateChannel: true }).content.includes('限制'), '案件負責人可綁定私密頻道');
const restricted = store.getCase(c.id); check(channelAccess(restricted, 'private') && !channelAccess(restricted, 'public'), '禁止跨頻道存取限制案件');
check(!store.listCases('test-guild').some(x => x.id === c.id), '限制案件排除於跨案件清單'); check(store.fileIsRestricted(saved.key), '限制案件既有檔案停止公開下载');
const blocked = onCommand('use', { name: c.name }, { ...ctx, channelId: 'public' }); check(blocked.includes('私密頻道'), '切換限制案件不能繞過頻道限制');
check(onCommand('versions', { name: 'v-test' }, ctx).files[0].buffer.equals(withImage), '私密頻道可下載原版');
console.log(`Passed ${count} consultant checks.`);
const { onMessage } = await import('../src/brain.js');
const posts = [], io = { channelId: 'private', say: async text => posts.push({ content: text }), typing: () => () => {}, post: async payload => { posts.push(payload); return { edit: async update => posts.push(update) }; } };
LLM.setLLM({ text: async () => ({ text: '不在範圍<<<KM_ACTIONS>>>\n{"in_scope":false,"tasks":[]}', usage: {} }) });
const originalFetch = globalThis.fetch;
globalThis.fetch = async () => new Response(JSON.stringify({ data: [{ b64_json: png.toString('base64') }] }), { status: 200, headers: { 'content-type': 'application/json' } });
cfg.imageModel = 'test-image';
const message = { id: 'test-image-' + Date.now(), channelId: 'private', guildId: 'test-guild', author: { id: 'owner', name: '顧問' }, text: '請在訪綱加入企業主管喝咖啡的示意圖', mentionsMe: true, allowed: true, attachments: [] };
await onMessage(message, io);
check(posts.some(p => p.files?.some(f => f.name.endsWith('.png'))) && posts.some(p => p.files?.some(f => f.name.endsWith('.docx'))), '路由即使婉拒，文件配圖明確交辦仍實際交付 PNG 與 Word');
const emittedWord = posts.flatMap(p => p.files || []).find(f => f.name.endsWith('.docx'));
check(Object.keys((await JSZip.loadAsync(emittedWord.buffer)).files).some(n => n.startsWith('word/media/') && n.endsWith('.png')), 'Discord 交付的 Word 確實含圖片');
const beforeVersions = store.getCase(c.id).versions.length; posts.length = 0;
globalThis.fetch = async () => new Response('{}', { status: 503 });
await onMessage({ ...message, id: message.id + '-fail' }, io);
check(posts.some(p => p.content?.includes('沒有完成')) && !posts.some(p => p.files?.length) && store.getCase(c.id).versions.length === beforeVersions, '圖片 API 失敗不交付空配圖文件、不記錄成功版本');
globalThis.fetch = originalFetch;
console.log(`Total ${count} consultant checks passed.`);
